USE [Spark2018]
GO

INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 6'), 'A', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 7' and Color = 'Black' and Storage = '32GB'), 'BA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 7' and Color = 'Black' and Storage = '128GB'), 'BB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Space Grey' and Storage = '64GB'), 'CA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Silver' and Storage = '64GB'), 'CB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Gold' and Storage = '64GB'), 'CC', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Space Grey' and Storage = '256GB'), 'CD', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Silver' and Storage = '256GB'), 'CE', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8' and Color = 'Gold' and Storage = '256GB'), 'CF', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8 Plus' and Color = 'Space Grey' and Storage = '64GB'), 'C1A', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8 Plus' and Color = 'Space Grey' and Storage = '256GB'), 'C1B', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone 8 Plus' and Color = 'Gold' and Storage = '64GB'), 'C1C', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone X' and Color = 'Space Grey' and Storage = '64GB'), 'DA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone X' and Color = 'Silver' and Storage = '64GB'), 'DB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone X' and Color = 'Space Grey' and Storage = '256GB'), 'DC', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'iPhone X' and Color = 'Silver' and Storage = '256GB'), 'DE', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J2 Prime'), 'E', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J2 Pro' and Color = 'Black' and Storage = '16GB'), 'FA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J2 Pro' and Color = 'Blue' and Storage = '16GB'), 'FB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy XCover4'), 'G', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J3 Pro' and Color = 'Black' and Storage = '16GB'), 'HA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J3 Pro' and Color = 'Gold' and Storage = '16GB'), 'HB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy J5 Pro' and Color = 'Black' and Storage = '32GB'), 'HC', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy A8'), 'I', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy A8+'), 'I1', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S8'), 'J', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy Note8' and Color = 'Black' and Storage = '64GB'), 'KA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy Note8' and Color = 'Gold' and Storage = '64GB'), 'KB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9' and Color = 'Purple' and Storage = '64GB'), 'LA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9' and Color = 'Black' and Storage = '64GB'), 'LB', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9' and Color = 'Black' and Storage = '256GB'), 'LC', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9' and Color = 'Blue' and Storage = '64GB'), 'LD', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9+' and Color = 'Purple' and Storage = '64GB'), 'L1A', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9+' and Color = 'Purple' and Storage = '256GB'), 'L1B', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9+' and Color = 'Blue' and Storage = '64GB'), 'L1C', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9+' and Color = 'Black' and Storage = '64GB'), 'L1D', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Galaxy S9+' and Color = 'Black' and Storage = '256GB'), 'L1E', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '3310 3G' and Color = 'Grey'), 'M', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '3310 3G' and Color = 'Red'), 'M1', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '2'), 'N', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '3'), 'O', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '5' and Color = 'Black'), 'P', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '5' and Color = 'Silver'), 'PA', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = '8'), 'Q', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Trio SIM'), 'R', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'LITE 3G'), 'S', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'POCKET'), 'T', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Plus 2'), 'U', 2000)
INSERT INTO [dbo].[Inventory.Product] VALUES ((select ProductID from [Supplier.Product] where Name = 'Xperia XA'), 'V', 2000)
GO


