USE [Spark2018]
GO

INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 6', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '32GB', 599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 7', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black', '32GB', 999)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 7', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '128GB',1199)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '64GB', 1249)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Silver', '64GB', 1249)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Gold', '64GB', 1249)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '256GB', 1549)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Silver', '256GB', 1549)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Gold', '256GB', 1549)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8 Plus', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '64GB', 1449)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8 Plus', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '256GB', 1749)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone 8 Plus', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Gold', '64GB', 1449)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone X', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '64GB', 1749)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone X', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Silver', '64GB', 1749)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone X', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Space Grey', '256GB', 2099)
INSERT INTO [dbo].[Supplier.Product] VALUES ('iPhone X', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Silver', '256GB', 2099)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J2 Prime', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black', '8GB', 249)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J2 Pro', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black', '16GB', 529)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J2 Pro', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Blue', '16GB', 529)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy XCover4', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '16GB', 399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J3 Pro', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '16GB', 399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J3 Pro', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Gold', '16GB', 399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy J5 Pro', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '32GB', 549)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy A8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black', '32GB', 699)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy A8+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black' , '32GB', 799)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '64GB', 1149)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy Note8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Black','64GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy Note8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Gold', '64GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'),'Purple', '64GB', 1399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '64GB', 1399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '256GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Blue', '64GB', 1399)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Purple', '64GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Purple', '256GB', 1799)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Blue', '64GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '64GB', 1599)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Galaxy S9+', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '256GB', 1799)
INSERT INTO [dbo].[Supplier.Product] VALUES ('3310 3G', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Grey', '64MB', 99)
INSERT INTO [dbo].[Supplier.Product] VALUES ('3310 3G', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Red', '64MB',99)
INSERT INTO [dbo].[Supplier.Product] VALUES ('2', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '8GB', 169)
INSERT INTO [dbo].[Supplier.Product] VALUES ('3', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '16GB', 249)
INSERT INTO [dbo].[Supplier.Product] VALUES ('5', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '16GB', 349)
INSERT INTO [dbo].[Supplier.Product] VALUES ('5', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Silver', '16GB', 349)
INSERT INTO [dbo].[Supplier.Product] VALUES ('8', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Blue', '64GB', 749)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Trio SIM', (select CategoryID from [Supplier.Category] where CategoryName = 'SIM'), null, null, 5)
INSERT INTO [dbo].[Supplier.Product] VALUES ('LITE 3G', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '4GB', 79)
INSERT INTO [dbo].[Supplier.Product] VALUES ('POCKET', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '64MB', 129)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Plus 2', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '8GB', 129)
INSERT INTO [dbo].[Supplier.Product] VALUES ('Xperia XA', (select CategoryID from [Supplier.Category] where CategoryName = 'Phone'), 'Black', '16GB', 249)
GO


